version: '2'
services:
  tao:
    image: sorrell/docker-tao-web
    links:
      - pgdb
    ports:
      - "80:80"
  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD:${TAO_POSTGRES_PASSWORD}
